// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxJkzIYfn3plq6RoHyz-TL8WJ4nUQYeZA',
    appId: '1:293751067507:web:f89d226819c1a15bb5eb06',
    messagingSenderId: '293751067507',
    projectId: 'foodbuddy-9558e',
    authDomain: 'foodbuddy-9558e.firebaseapp.com',
    storageBucket: 'foodbuddy-9558e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa9bwrOpB0FFjmyVwXJACSOWgf9FUfTJU',
    appId: '1:293751067507:android:8c1f6c6705bea8bbb5eb06',
    messagingSenderId: '293751067507',
    projectId: 'foodbuddy-9558e',
    storageBucket: 'foodbuddy-9558e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNFqakkY2urkJTSNdDVMcbhcGJS3uIAwU',
    appId: '1:293751067507:ios:cb4ffda2e06d301fb5eb06',
    messagingSenderId: '293751067507',
    projectId: 'foodbuddy-9558e',
    storageBucket: 'foodbuddy-9558e.appspot.com',
    iosClientId:
        '293751067507-d913rumb841c1al7fo6nmsvfkk7ah3ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNFqakkY2urkJTSNdDVMcbhcGJS3uIAwU',
    appId: '1:293751067507:ios:21a24aee6bf2c3c1b5eb06',
    messagingSenderId: '293751067507',
    projectId: 'foodbuddy-9558e',
    storageBucket: 'foodbuddy-9558e.appspot.com',
    iosClientId:
        '293751067507-v1d1t80ol24c47dmferbkqg3otfbcj2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodbuddy.RunnerTests',
  );
}
